# Generated by Django 3.2.6 on 2021-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
