# Generated by Django 3.2.6 on 2021-08-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remote_bookings',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
