# Generated by Django 3.2.6 on 2021-08-26 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_auto_20210826_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpayment',
            name='payment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 26, 11, 27, 3, 343543, tzinfo=utc)),
        ),
    ]
