# Generated by Django 3.2.6 on 2021-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planner',
        ),
    ]
