# Generated by Django 3.2.6 on 2021-08-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
