# Generated by Django 3.2.6 on 2021-08-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_remove_userprofile_name'),
        ('planner', '0002_alter_plans_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='book',
            name='day',
            field=models.ManyToManyField(to='planner.Plans'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(choices=[('6:00-7:30', '6:00-7:30'), ('7:30-9:00', '7:30-9:00'), ('9:00-11:30', '9:00-11:30'), ('11:30-1:00', '11:30-1:00'), ('2:00-4:30', '2:00-4:30'), ('4:30-6:00', '4:30-6:00'), ('6:00-7:30', '6:00-7:30')], max_length=200),
        ),
        migrations.CreateModel(
            name='MyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=200)),
                ('progress', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.userprofile')),
            ],
        ),
    ]
