# Generated by Django 3.2.6 on 2021-08-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_remove_book_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='day',
            field=models.OneToOneField(default=23, on_delete=django.db.models.deletion.CASCADE, to='planner.plans'),
            preserve_default=False,
        ),
    ]
