# Generated by Django 3.2.6 on 2021-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_book_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thur', 'Thur'), ('Fri', 'Fri')], max_length=200),
        ),
    ]
