# Generated by Django 3.2.6 on 2021-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_alter_book_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={},
        ),
        migrations.RenameField(
            model_name='plans',
            old_name='target',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='day',
        ),
        migrations.AlterField(
            model_name='plans',
            name='workout',
            field=models.CharField(choices=[('aerobics', 'aerobics'), ('Group class', 'Group class'), ('personal trainer', 'personal trainer')], default=12, max_length=200),
            preserve_default=False,
        ),
    ]
