# Generated by Django 3.2.6 on 2021-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20210822_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='time',
            field=models.CharField(choices=[('6:00-7:30', '6:00-7:30'), ('7:30-9:00', '7:30-9:00'), ('9:00-11:30', '9:00-11:30'), ('11:30-1:00', '11:30-1:00'), ('2:00-4:30', '2:00-4:30'), ('4:30-6:00', '4:30-6:00'), ('6:00-7:30', '6:00-7:30')], default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
