# Generated by Django 3.2.6 on 2021-08-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20210822_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='workout',
            field=models.CharField(choices=[('aerobics', 'aerobics'), ('Group class', 'Group class'), ('personal trainer', 'personal trainer'), ('solo training', 'solo training')], max_length=200),
        ),
    ]
