# Generated by Django 3.2.6 on 2021-08-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_userprofile_profile_photo'),
        ('planner', '0012_alter_book_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('workout', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.userprofile')),
            ],
        ),
    ]
