# Generated by Django 3.2.6 on 2021-08-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_myschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProgress',
        ),
    ]
