# Generated by Django 3.2.6 on 2021-08-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_delete_myprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myschedule',
            name='user',
        ),
    ]
