# Generated by Django 3.2.6 on 2021-08-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_userprofile_profile_photo'),
        ('planner', '0015_remove_myschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myschedule',
            name='user',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='gym.userprofile'),
            preserve_default=False,
        ),
    ]
