# Generated by Django 3.2.6 on 2021-08-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_myschedule_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySchedule',
        ),
    ]
