# Generated by Django 3.2.6 on 2021-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_delete_myschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='days',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='workout',
            field=models.CharField(choices=[('aerobics', 'aerobics'), ('Group classes', 'Group classes'), ('personal trainer', 'personal trainer')], max_length=200),
        ),
    ]
